### ISSUE TITLE
Running on UCF-101 Dataset

### ISSUE THREAD

**Issue by matthewkol186** [wuzhenyusjtu/Privacy-AdversarialLearning#1]
Hi there,

Thank you so much for making this GitHub repo! My team is attempting to replicate on the UCF-101 dataset. So far, we have run the following steps:

- Downloaded the UCF101 and UCF101 train test splits for the action recognition task
- Run `ShuffleEvenlyDistributeFiles.py` to create the UCF-101_shuffled folder
- Run `convert2records.py` to convert the folders in UCF-101_shuffled/ to  a list of `test_*.tfrecords` and `train_*.tfrecords` files
- Moved around the files generated above inside a `data/train` and `data/test` folder
- Run `run_gpu.py` (had to modify the `height` and `width` flags in `tf_flags.py` to 112, because we previously got a dimensions error)

At this point, we encounter this issue: 

```
Session restored from pretrained model at /vision2/u/ejchou/mattsun/vispr_data/checkpoint/pretrained/C3D/conv3d_deepnetA_sport1m_iter_1900000_TF.model!
Traceback (most recent call last):
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_2_input/batching_shuffling/random_shuffle_queue' is closed and has insufficient elements (requested 64, curr
ent size 0)
         [[Node: input/batching_shuffling = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](input/batching
_shuffling/random_shuffle_queue, input/batching_shuffling/n)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_gpu.py", line 328, in <module>
    tf.app.run()
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_gpu.py", line 324, in main
    run_training()
  File "run_gpu.py", line 195, in run_training
    tr_videos, tr_labels = sess.run([tr_videos_op, tr_labels_op])
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_2_input/batching_shuffling/random_shuffle_queue' is closed and has insufficient elements (requested 64, curr
ent size 0)
         [[Node: input/batching_shuffling = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](input/batching
_shuffling/random_shuffle_queue, input/batching_shuffling/n)]]
Caused by op 'input/batching_shuffling', defined at:
  File "run_gpu.py", line 328, in <module>
    tf.app.run()
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_gpu.py", line 324, in main
    run_training()
  File "run_gpu.py", line 155, in run_training
    num_examples_per_epoch=FLAGS.num_examples_per_epoch)
  File "/vision2/u/ejchou/mattsun/vispr_pac/Privacy-AdversarialLearning/UCF+VISPR/ucf101/input_data.py", line 53, in inputs
    name='batching_shuffling'
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 1300, in shuffle_batch
    name=name)
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 846, in _shuffle_batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/ops/data_flow_ops.py", line 476, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3480, in queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/vision2/u/ejchou/anaconda3/envs/tf3gpu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): RandomShuffleQueue '_2_input/batching_shuffling/random_shuffle_queue' is closed and has insufficient elements (requested 64, current size 0)
         [[Node: input/batching_shuffling = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](input/batching_shuffling/random_shuffle_queue, input/batching_shuffling/n)]]
```

I'm very confused about this error. Do you have any advice on what might be going on?

**Comment by Anirudh1097** [comment]
I have been running into the same issue--would appreciate any advice!
